package typescript

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/terminally-online/shrugged/internal/codegen"
	"github.com/terminally-online/shrugged/internal/parser"
)

func init() {
	codegen.Register(&TypeScriptGenerator{})
}

// TypeScriptGenerator generates TypeScript interfaces from a Postgres schema.
type TypeScriptGenerator struct{}

func (g *TypeScriptGenerator) Language() string {
	return "typescript"
}

func (g *TypeScriptGenerator) Generate(schema *parser.Schema, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	for _, enum := range schema.Enums {
		if err := g.generateEnum(enum, outDir); err != nil {
			return fmt.Errorf("failed to generate enum %s: %w", enum.Name, err)
		}
	}

	for _, ct := range schema.CompositeTypes {
		if err := g.generateCompositeType(ct, outDir); err != nil {
			return fmt.Errorf("failed to generate composite type %s: %w", ct.Name, err)
		}
	}

	for _, table := range schema.Tables {
		if table.Name == "shrugged_migrations" {
			continue
		}
		if err := g.generateTable(table, schema, outDir); err != nil {
			return fmt.Errorf("failed to generate table %s: %w", table.Name, err)
		}
	}

	return nil
}

// GenerateQueries is not supported for TypeScript — query bindings are a future addition.
func (g *TypeScriptGenerator) GenerateQueries(opts codegen.QueryGenOptions) ([]string, error) {
	return nil, fmt.Errorf("typescript query generation is not yet supported")
}

func (g *TypeScriptGenerator) generateEnum(enum parser.Enum, outDir string) error {
	typeName := toPascalCase(enum.Name)
	fileName := toKebabCase(enum.Name) + ".ts"
	filePath := filepath.Join(outDir, fileName)

	var sb strings.Builder
	sb.WriteString("// Code generated by shrugged. DO NOT EDIT.\n\n")

	fmt.Fprintf(&sb, "export type %s =\n", typeName)
	for i, value := range enum.Values {
		if i < len(enum.Values)-1 {
			fmt.Fprintf(&sb, "  | %q\n", value)
		} else {
			fmt.Fprintf(&sb, "  | %q;\n", value)
		}
	}

	return os.WriteFile(filePath, []byte(sb.String()), 0o644)
}

func (g *TypeScriptGenerator) generateCompositeType(ct parser.CompositeType, outDir string) error {
	typeName := toPascalCase(ct.Name)
	fileName := toKebabCase(ct.Name) + ".ts"
	filePath := filepath.Join(outDir, fileName)

	var sb strings.Builder
	sb.WriteString("// Code generated by shrugged. DO NOT EDIT.\n\n")

	fmt.Fprintf(&sb, "export interface %s {\n", typeName)
	for _, attr := range ct.Attributes {
		tsType := pgTypeToTS(attr.Type, attr.Nullable, nil)
		propName := toCamelCase(attr.Name)
		fmt.Fprintf(&sb, "  %s: %s;\n", propName, tsType)
	}
	sb.WriteString("}\n")

	return os.WriteFile(filePath, []byte(sb.String()), 0o644)
}

func (g *TypeScriptGenerator) generateTable(table parser.Table, schema *parser.Schema, outDir string) error {
	typeName := toPascalCase(table.Name)
	fileName := toKebabCase(table.Name) + ".ts"
	filePath := filepath.Join(outDir, fileName)

	var sb strings.Builder
	sb.WriteString("// Code generated by shrugged. DO NOT EDIT.\n\n")

	fmt.Fprintf(&sb, "export interface %s {\n", typeName)
	for _, col := range table.Columns {
		tsType := pgTypeToTS(col.Type, col.Nullable, schema)
		propName := toCamelCase(col.Name)
		fmt.Fprintf(&sb, "  %s: %s;\n", propName, tsType)
	}
	sb.WriteString("}\n")

	return os.WriteFile(filePath, []byte(sb.String()), 0o644)
}

// pgTypeToTS maps a Postgres type to its TypeScript equivalent.
// Nullable columns are represented as T | null.
// Array types are represented as T[].
func pgTypeToTS(pgType string, nullable bool, schema *parser.Schema) string {
	pgType = strings.ToLower(strings.TrimSpace(pgType))

	isArray := strings.HasSuffix(pgType, "[]") || strings.HasPrefix(pgType, "array")
	if isArray {
		pgType = strings.TrimSuffix(pgType, "[]")
		pgType = strings.TrimPrefix(pgType, "array[")
		pgType = strings.TrimSuffix(pgType, "]")
	}

	if strings.HasPrefix(pgType, "character varying") || strings.HasPrefix(pgType, "varchar") {
		pgType = "varchar"
	}
	if strings.HasPrefix(pgType, "character(") || strings.HasPrefix(pgType, "char(") {
		pgType = "char"
	}
	if strings.HasPrefix(pgType, "numeric") || strings.HasPrefix(pgType, "decimal") {
		pgType = "numeric"
	}
	if strings.HasPrefix(pgType, "timestamp") {
		if strings.Contains(pgType, "with time zone") {
			pgType = "timestamptz"
		} else {
			pgType = "timestamp"
		}
	}
	if strings.HasPrefix(pgType, "time ") {
		if strings.Contains(pgType, "with time zone") {
			pgType = "timetz"
		} else {
			pgType = "time"
		}
	}

	var baseType string

	switch pgType {
	case "integer", "int", "int4", "smallint", "int2", "real", "float4", "double precision", "float8":
		baseType = "number"
	case "bigint", "int8":
		baseType = "bigint"
	case "boolean", "bool":
		baseType = "boolean"
	case "text", "varchar", "char", "name":
		baseType = "string"
	case "bytea":
		baseType = "string"
	case "uuid":
		baseType = "string"
	case "json", "jsonb":
		baseType = "Record<string, unknown>"
	case "timestamp", "timestamptz", "date", "time", "timetz":
		baseType = "Date"
	case "interval":
		baseType = "string"
	case "numeric", "money":
		// Preserve decimal precision — string avoids float64 rounding.
		baseType = "string"
	case "inet", "cidr", "macaddr", "macaddr8":
		baseType = "string"
	case "bit", "bit varying", "varbit":
		baseType = "string"
	case "xml":
		baseType = "string"
	case "point", "line", "lseg", "box", "path", "polygon", "circle":
		baseType = "string"
	case "tsquery", "tsvector":
		baseType = "string"
	case "oid":
		baseType = "number"
	default:
		if schema != nil {
			for _, e := range schema.Enums {
				if strings.ToLower(e.Name) == pgType {
					baseType = toPascalCase(e.Name)
					goto done
				}
			}
			for _, c := range schema.CompositeTypes {
				if strings.ToLower(c.Name) == pgType {
					baseType = toPascalCase(c.Name)
					goto done
				}
			}
		}
		baseType = toPascalCase(pgType)
	}

done:
	var tsType string
	if isArray {
		tsType = baseType + "[]"
	} else {
		tsType = baseType
	}

	if nullable {
		tsType = tsType + " | null"
	}

	return tsType
}

// toPascalCase converts snake_case or kebab-case to PascalCase.
func toPascalCase(s string) string {
	words := splitWords(s)
	var result strings.Builder
	for _, word := range words {
		if len(word) == 0 {
			continue
		}
		result.WriteString(strings.ToUpper(string(word[0])))
		result.WriteString(strings.ToLower(word[1:]))
	}
	return result.String()
}

// toCamelCase converts snake_case or kebab-case to camelCase.
func toCamelCase(s string) string {
	words := splitWords(s)
	var result strings.Builder
	for i, word := range words {
		if len(word) == 0 {
			continue
		}
		if i == 0 {
			result.WriteString(strings.ToLower(word))
		} else {
			result.WriteString(strings.ToUpper(string(word[0])))
			result.WriteString(strings.ToLower(word[1:]))
		}
	}
	return result.String()
}

// toKebabCase converts snake_case to kebab-case for file names.
func toKebabCase(s string) string {
	return strings.ReplaceAll(s, "_", "-")
}

func splitWords(s string) []string {
	return strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
}
